FROM alpine:latest AS prep
RUN apk --update add ca-certificates

FROM ubuntu:22.04

ARG USER_UID=10001
ARG USER_GID=10001

COPY --from=prep /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY bin/otelcontribcol1/otelcontribcol /otelcontribcol
COPY config.yaml /etc/otel/config.yaml

RUN chmod +x /otelcontribcol

USER ${USER_UID}:${USER_GID}

EXPOSE 4317 55680 55679 8888

ENTRYPOINT ["/otelcontribcol"]
CMD ["--config", "/etc/otel/config.yaml"]
